# Generated by Django 5.0 on 2024-12-13 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_maquina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Benfeitoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_benfeitoria', models.CharField(max_length=50, verbose_name='ID da Benfeitoria')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Compra')),
                ('valor_residual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Residual')),
                ('vida_util', models.IntegerField(verbose_name='Vida Útil (anos)')),
                ('data_aquisicao', models.DateField(verbose_name='Data de Aquisição')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fazenda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Benfeitoria',
                'verbose_name_plural': 'Benfeitorias',
                'ordering': ['nome'],
            },
        ),
    ]
