# Generated by Django 5.0 on 2024-12-13 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_benfeitoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco')),
                ('agencia', models.CharField(max_length=20, verbose_name='Agência')),
                ('conta', models.CharField(max_length=20, verbose_name='Número da Conta')),
                ('tipo', models.CharField(choices=[('CC', 'Conta Corrente'), ('CP', 'Conta Poupança'), ('CI', 'Conta Investimento')], max_length=2, verbose_name='Tipo de Conta')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Atual')),
                ('data_saldo', models.DateField(verbose_name='Data do Saldo')),
                ('ativa', models.BooleanField(default=True, verbose_name='Conta Ativa')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('fazenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fazenda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
                'ordering': ['banco', 'agencia', 'conta'],
                'unique_together': {('banco', 'agencia', 'conta', 'usuario')},
            },
        ),
    ]
