# Generated by Django 5.0 on 2024-12-13 01:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contabancaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contabancaria',
            name='agencia',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Agência'),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='conta',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número da Conta'),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='data_saldo',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data do Saldo'),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='fazenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fazenda'),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='tipo',
            field=models.CharField(choices=[('CC', 'Conta Corrente'), ('CP', 'Conta Poupança'), ('CI', 'Conta Investimento')], default='CC', max_length=2, verbose_name='Tipo de Conta'),
        ),
    ]
