# Generated by Django 5.0 on 2024-12-13 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_create_despesa_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alocacaodespesa',
            options={},
        ),
        migrations.AddField(
            model_name='alocacaodespesa',
            name='tipo_alocacao',
            field=models.CharField(choices=[('fazenda', 'Fazenda'), ('lote', 'Lote'), ('maquina', 'Máquina'), ('benfeitoria', 'Benfeitoria'), ('pasto', 'Pasto/Curral')], default='fazenda', max_length=20),
        ),
        migrations.AlterField(
            model_name='alocacaodespesa',
            name='benfeitoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.benfeitoria'),
        ),
        migrations.AlterField(
            model_name='alocacaodespesa',
            name='fazenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fazenda'),
        ),
        migrations.AlterField(
            model_name='alocacaodespesa',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lote'),
        ),
        migrations.AlterField(
            model_name='alocacaodespesa',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.maquina'),
        ),
        migrations.AlterField(
            model_name='alocacaodespesa',
            name='pasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pasto'),
        ),
    ]
