# Generated by Django 5.0 on 2024-12-13 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_alocacaodespesa_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rateiodespesa',
            name='alocacao',
        ),
        migrations.RemoveField(
            model_name='rateiodespesa',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='itemdespesa',
            name='observacao',
        ),
        migrations.AddField(
            model_name='itemdespesa',
            name='benfeitoria_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.benfeitoria'),
        ),
        migrations.AddField(
            model_name='itemdespesa',
            name='fazenda_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.fazenda'),
        ),
        migrations.AddField(
            model_name='itemdespesa',
            name='lote_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.lote'),
        ),
        migrations.AddField(
            model_name='itemdespesa',
            name='maquina_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.maquina'),
        ),
        migrations.AddField(
            model_name='itemdespesa',
            name='pastagem_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.pasto'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='forma_pagamento',
            field=models.CharField(choices=[('AV', 'À Vista'), ('PR', 'Parcelado')], max_length=2, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='itemdespesa',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade'),
        ),
        migrations.CreateModel(
            name='RateioCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_rateio', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.animal')),
                ('item_despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.itemdespesa')),
            ],
            options={
                'verbose_name': 'Rateio de Custo',
                'verbose_name_plural': 'Rateios de Custos',
            },
        ),
        migrations.DeleteModel(
            name='AlocacaoDespesa',
        ),
        migrations.DeleteModel(
            name='RateioDespesa',
        ),
    ]
