# Generated by Django 5.0 on 2024-12-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_rateiodespesa_alocacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='categoriacusto',
            name='tipo',
            field=models.CharField(choices=[('investimento', 'Investimento'), ('fixo', 'Custo Fixo'), ('variavel', 'Custo Variável')], default='fixo', max_length=20),
        ),
    ]
