# Generated by Django 5.0 on 2024-12-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_parceladespesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='data_cadastro',
        ),
        migrations.AddField(
            model_name='despesa',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='multa_juros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Multa/Juros'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='parceladespesa',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto'),
        ),
        migrations.AddField(
            model_name='parceladespesa',
            name='multa_juros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Multa/Juros'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='numero_nf',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número NF'),
        ),
    ]
