# Generated by Django 5.0 on 2024-12-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_despesa_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='parceladespesa',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10, verbose_name='Status'),
        ),
    ]
