# Generated by Django 5.0 on 2025-01-08 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_despesa_status_alter_parceladespesa_status'),
    ]

    operations = [
    ]
