# Generated by Django 5.0 on 2025-01-09 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_motivomorte_usuario_variedadecapim_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriacusto',
            options={'ordering': ['tipo', 'nome'], 'verbose_name': 'Categoria de Custo', 'verbose_name_plural': 'Categorias de Custo'},
        ),
        migrations.AlterModelOptions(
            name='finalidadelote',
            options={'ordering': ['nome'], 'verbose_name': 'Finalidade do Lote', 'verbose_name_plural': 'Finalidades dos Lotes'},
        ),
        migrations.AlterModelOptions(
            name='subcategoriacusto',
            options={'ordering': ['categoria__tipo', 'categoria__nome', 'nome'], 'verbose_name': 'Subcategoria de Custo', 'verbose_name_plural': 'Subcategorias de Custo'},
        ),
        migrations.AlterUniqueTogether(
            name='categoriaanimal',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subcategoriacusto',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='unidademedida',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='categoriaanimal',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoriacusto',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finalidadelote',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='raca',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcategoriacusto',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unidademedida',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoriacusto',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='categoriacusto',
            name='tipo',
            field=models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10),
        ),
        migrations.AlterField(
            model_name='finalidadelote',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='raca',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subcategoriacusto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriacusto'),
        ),
        migrations.AlterUniqueTogether(
            name='categoriaanimal',
            unique_together={('nome', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='categoriacusto',
            unique_together={('nome', 'tipo', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='finalidadelote',
            unique_together={('nome', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='raca',
            unique_together={('nome', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='subcategoriacusto',
            unique_together={('nome', 'categoria', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='unidademedida',
            unique_together={('nome', 'usuario')},
        ),
    ]
