# Generated by Django 5.0 on 2025-01-10 00:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_categoriacusto_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriacusto',
            options={'ordering': ['nome'], 'verbose_name': 'Categoria de Custo', 'verbose_name_plural': 'Categorias de Custos'},
        ),
        migrations.AlterModelOptions(
            name='finalidadelote',
            options={'ordering': ['nome'], 'verbose_name': 'Finalidade de Lote', 'verbose_name_plural': 'Finalidades de Lote'},
        ),
        migrations.AlterModelOptions(
            name='subcategoriacusto',
            options={'ordering': ['categoria__nome', 'nome'], 'verbose_name': 'Subcategoria de Custo', 'verbose_name_plural': 'Subcategorias de Custos'},
        ),
        migrations.AlterUniqueTogether(
            name='categoriacusto',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='finalidadelote',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='motivomorte',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='raca',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='variedadecapim',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='categoriaanimal',
            unique_together={('nome', 'sexo')},
        ),
        migrations.AlterUniqueTogether(
            name='subcategoriacusto',
            unique_together={('categoria', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='unidademedida',
            unique_together={('nome', 'tipo')},
        ),
        migrations.AlterField(
            model_name='categoriacusto',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='categoriacusto',
            name='tipo',
            field=models.CharField(choices=[('investimento', 'Investimento'), ('fixo', 'Custo Fixo'), ('variavel', 'Custo Variável')], default='fixo', max_length=20),
        ),
        migrations.AlterField(
            model_name='finalidadelote',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='motivomorte',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='raca',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategoriacusto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='core.categoriacusto'),
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Insumo')),
                ('saldo_estoque', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo em Estoque')),
                ('preco_medio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Médio')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(limit_choices_to={'alocacao': 'estoque'}, on_delete=django.db.models.deletion.PROTECT, to='core.categoriacusto')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.subcategoriacusto')),
                ('unidade_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unidademedida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nome'],
                'unique_together': {('nome', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída'), ('SN', 'Saída Nutrição')], max_length=2, verbose_name='Tipo')),
                ('data', models.DateField(verbose_name='Data')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('despesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.despesa')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destino_movimentacoes', to='core.pasto')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='core.insumo')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lote')),
                ('pasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pasto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data', '-data_cadastro'],
            },
        ),
        migrations.RemoveField(
            model_name='categoriacusto',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='finalidadelote',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='motivomorte',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='raca',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='variedadecapim',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='categoriaanimal',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='subcategoriacusto',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='unidademedida',
            name='usuario',
        ),
    ]
