# Generated by Django 5.0 on 2025-01-10 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_unidademedida_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateioMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.animal')),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movimentacaoestoque')),
            ],
            options={
                'db_table': 'rateio_movimentacao',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
