# Generated by Django 5.0 on 2025-01-10 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rateiomovimentacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='destino',
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='destino_lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destino_movimentacoes', to='core.lote'),
        ),
    ]
