# Generated by Django 5.0 on 2025-01-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_movimentacaoestoque_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='consumo_pv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Consumo % Peso Vivo'),
        ),
    ]
