# Generated by Django 5.0 on 2025-01-15 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_categoriacusto_nome_alter_motivomorte_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='animal',
        ),
        migrations.CreateModel(
            name='CompraAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.animal')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='core.compra')),
            ],
            options={
                'verbose_name': 'Animal da Compra',
                'verbose_name_plural': 'Animais da Compra',
                'unique_together': {('compra', 'animal')},
            },
        ),
    ]
