# Generated by Django 5.0 on 2025-01-15 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_compra_animal_compraanimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='intervalo_parcelas',
            field=models.IntegerField(choices=[(30, 'Mensal'), (15, 'Quinzenal'), (7, 'Semanal')], default=30, verbose_name='Intervalo de Parcelas'),
        ),
        migrations.AddField(
            model_name='compra',
            name='numero_parcelas',
            field=models.IntegerField(default=1, verbose_name='Número de Parcelas'),
        ),
        migrations.CreateModel(
            name='ParcelaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido')], default='PENDENTE', max_length=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='core.compra')),
            ],
            options={
                'ordering': ['data_vencimento'],
                'unique_together': {('compra', 'numero')},
            },
        ),
    ]
