# Generated by Django 5.0 on 2025-01-15 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_compra_intervalo_parcelas_compra_numero_parcelas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelacompra',
            name='data_pagamento',
        ),
        migrations.AlterField(
            model_name='parcelacompra',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Parcialmente Pago'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido')], default='PENDENTE', max_length=10),
        ),
        migrations.CreateModel(
            name='PagamentoParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contabancaria')),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.parcelacompra')),
            ],
            options={
                'ordering': ['-data_pagamento'],
            },
        ),
    ]
