# Generated by Django 5.0 on 2025-01-15 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_parcelacompra_data_pagamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelaVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Parcialmente Pago'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido')], default='PENDENTE', max_length=10)),
            ],
            options={
                'verbose_name': 'Parcela da Venda',
                'verbose_name_plural': 'Parcelas da Venda',
                'ordering': ['data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoParcelaVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contabancaria')),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.parcelavenda')),
            ],
            options={
                'verbose_name': 'Pagamento de Parcela da Venda',
                'verbose_name_plural': 'Pagamentos de Parcelas da Venda',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Venda')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('tipo_venda', models.CharField(choices=[('UN', 'Por Unidade'), ('KG', 'Por Kg')], max_length=2, verbose_name='Tipo de Venda')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10, verbose_name='Status')),
                ('numero_parcelas', models.IntegerField(default=1, verbose_name='Número de Parcelas')),
                ('intervalo_parcelas', models.IntegerField(choices=[(30, 'Mensal'), (15, 'Quinzenal'), (7, 'Semanal')], default=30, verbose_name='Intervalo de Parcelas')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contato', verbose_name='Comprador')),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contabancaria', verbose_name='Conta Bancária')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.AddField(
            model_name='parcelavenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='core.venda'),
        ),
        migrations.AlterUniqueTogether(
            name='parcelavenda',
            unique_together={('venda', 'numero')},
        ),
        migrations.CreateModel(
            name='VendaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.animal')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='core.venda')),
            ],
            options={
                'verbose_name': 'Animal da Venda',
                'verbose_name_plural': 'Animais da Venda',
                'unique_together': {('venda', 'animal')},
            },
        ),
    ]
