# Generated by Django 5.0 on 2025-01-15 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_parcelavenda_pagamentoparcelavenda_venda_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcelavenda',
            options={'ordering': ['numero'], 'verbose_name': 'Parcela de Venda', 'verbose_name_plural': 'Parcelas de Vendas'},
        ),
        migrations.AlterField(
            model_name='parcelavenda',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Parcial'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido')], default='PENDENTE', max_length=10),
        ),
        migrations.CreateModel(
            name='PagamentoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_venda', to='core.parcelavenda')),
            ],
            options={
                'verbose_name': 'Pagamento de Venda',
                'verbose_name_plural': 'Pagamentos de Vendas',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.DeleteModel(
            name='PagamentoParcelaVenda',
        ),
    ]
