# Generated by Django 5.0 on 2025-01-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_parcelavenda_options_alter_parcelavenda_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaanimal',
            name='peso_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso na Venda'),
        ),
        migrations.AddField(
            model_name='vendaanimal',
            name='valor_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor por Kg'),
        ),
        migrations.AlterField(
            model_name='vendaanimal',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total'),
        ),
    ]
