# Generated by Django 5.0 on 2025-01-15 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_vendaanimal_peso_venda_vendaanimal_valor_kg_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do Abate')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('valor_arroba', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor por @')),
                ('rendimento_padrao', models.DecimalField(decimal_places=2, help_text='Rendimento padrão de carcaça em porcentagem', max_digits=5, verbose_name='Rendimento Padrão (%)')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10, verbose_name='Status')),
                ('numero_parcelas', models.IntegerField(default=1, verbose_name='Número de Parcelas')),
                ('intervalo_parcelas', models.IntegerField(choices=[(30, 'Mensal'), (15, 'Quinzenal'), (7, 'Semanal')], default=30, verbose_name='Intervalo de Parcelas')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contato', verbose_name='Comprador')),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contabancaria', verbose_name='Conta Bancária')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abate',
                'verbose_name_plural': 'Abates',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaAbate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número da Parcela')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Pago')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10, verbose_name='Status')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('abate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='core.abate')),
            ],
            options={
                'verbose_name': 'Parcela do Abate',
                'verbose_name_plural': 'Parcelas do Abate',
                'ordering': ['data_vencimento', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoParcelaAbate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_pagamento', models.DateField(verbose_name='Data do Pagamento')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.parcelaabate')),
            ],
            options={
                'verbose_name': 'Pagamento de Parcela do Abate',
                'verbose_name_plural': 'Pagamentos de Parcelas do Abate',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.CreateModel(
            name='AbateAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_vivo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso Vivo (kg)')),
                ('rendimento', models.DecimalField(decimal_places=2, help_text='Rendimento de carcaça em porcentagem', max_digits=5, verbose_name='Rendimento (%)')),
                ('valor_arroba', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor por @')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('abate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='core.abate')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.animal')),
            ],
            options={
                'verbose_name': 'Animal do Abate',
                'verbose_name_plural': 'Animais do Abate',
                'unique_together': {('abate', 'animal')},
            },
        ),
    ]
