# Generated by Django 5.0 on 2025-01-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_abate_parcelaabate_pagamentoparcelaabate_abateanimal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abate',
            name='comprador',
        ),
        migrations.AlterField(
            model_name='abate',
            name='intervalo_parcelas',
            field=models.IntegerField(default=30, verbose_name='Intervalo de Parcelas'),
        ),
    ]
