# Generated by Django 5.0 on 2025-01-17 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_abate_comprador_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcelaabate',
            options={'ordering': ['numero'], 'verbose_name': 'Parcela do Abate', 'verbose_name_plural': 'Parcelas do Abate'},
        ),
        migrations.AddField(
            model_name='abate',
            name='comprador',
            field=models.ForeignKey(default=1, limit_choices_to={'tipo': 'CO'}, on_delete=django.db.models.deletion.PROTECT, related_name='abates', to='core.contato', verbose_name='Comprador'),
            preserve_default=False,
        ),
    ]
