# Generated by Django 5.0 on 2025-01-30 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_parcelaabate_options_abate_comprador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.contabancaria', verbose_name='Conta Bancária'),
        ),
        migrations.AddField(
            model_name='movimentacaonaooperacional',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='ExtratoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Movimentação')),
                ('tipo', models.CharField(choices=[('despesa', 'Despesa'), ('venda', 'Venda'), ('abate', 'Abate'), ('nao_operacional', 'Não Operacional')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Saldo Anterior')),
                ('saldo_atual', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Saldo Atual')),
                ('referencia_id', models.IntegerField(verbose_name='ID de Referência')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='core.contabancaria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extrato Bancário',
                'verbose_name_plural': 'Extratos Bancários',
                'ordering': ['-data', '-created_at'],
            },
        ),
    ]
