# Generated by Django 5.0 on 2025-02-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_populate_extrato_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='fazenda',
            name='timezone',
            field=models.CharField(choices=[('America/Manaus', 'Manaus (GMT-4)'), ('America/Sao_Paulo', 'São Paulo (GMT-3)'), ('America/Belem', 'Belém (GMT-3)'), ('America/Rio_Branco', 'Rio Branco (GMT-5)'), ('America/Cuiaba', 'Cuiabá (GMT-4)')], default='America/Sao_Paulo', max_length=50, verbose_name='Fuso Horário'),
        ),
    ]
