# Generated by Django 5.0 on 2025-02-10 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_fazenda_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstacaoMonta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fazenda')),
                ('lotes', models.ManyToManyField(related_name='estacoes_monta', to='core.lote')),
            ],
            options={
                'verbose_name': 'Estação de Monta',
                'verbose_name_plural': 'Estações de Monta',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ManejoReproducao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_concepcao', models.DateField(blank=True, null=True)),
                ('previsao_parto', models.DateField(blank=True, null=True)),
                ('data_diagnostico', models.DateField(blank=True, null=True)),
                ('diagnostico', models.CharField(blank=True, choices=[('PRENHE', 'Prenhe'), ('VAZIA', 'Vazia')], max_length=10, null=True)),
                ('data_resultado', models.DateField(blank=True, null=True)),
                ('resultado', models.CharField(blank=True, choices=[('NASCIMENTO', 'Nascimento'), ('PERDA_PREPARTO', 'Perda Pré-parto'), ('NATIMORTO', 'Natimorto')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.animal')),
                ('estacao_monta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estacaomonta')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lote')),
            ],
            options={
                'verbose_name': 'Manejo Reprodutivo',
                'verbose_name_plural': 'Manejos Reprodutivos',
                'ordering': ['-data_concepcao'],
            },
        ),
    ]
