# Generated by Django 5.0 on 2025-02-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_estacaomonta_manejoreproducao'),
    ]

    operations = [
        migrations.AddField(
            model_name='benfeitoria',
            name='coordenadas',
            field=models.JSONField(blank=True, help_text='Coordenadas do ponto no mapa (latitude, longitude)', null=True, verbose_name='Coordenadas do Ponto'),
        ),
    ]
