# Generated by Django 5.0 on 2025-02-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_benfeitoria_coordenadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abate',
            name='intervalo_parcelas',
            field=models.IntegerField(choices=[(30, 'Mensal'), (15, 'Quinzenal'), (7, 'Semanal')], default=30, verbose_name='Intervalo de Parcelas'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='benfeitoria',
            name='coordenadas',
            field=models.JSONField(blank=True, null=True, verbose_name='Coordenadas'),
        ),
        migrations.AlterField(
            model_name='benfeitoria',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Aquisição'),
        ),
        migrations.AlterField(
            model_name='benfeitoria',
            name='valor_residual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Residual'),
        ),
        migrations.AlterField(
            model_name='benfeitoria',
            name='vida_util',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vida Útil (anos)'),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fazenda',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movimentacaonaooperacional',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='movimentacaonaooperacional',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
