# Generated by Django 5.0 on 2025-02-14 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_update_data_cadastro_to_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['usuario', 'situacao'], name='core_animal_usuario_544308_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['fazenda_atual'], name='core_animal_fazenda_0e2daf_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['lote'], name='core_animal_lote_id_119473_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['pasto_atual'], name='core_animal_pasto_a_e3e23b_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['categoria_animal'], name='core_animal_categor_de0148_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['raca'], name='core_animal_raca_id_ce72ad_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['brinco_visual'], name='core_animal_brinco__7c3790_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['brinco_eletronico'], name='core_animal_brinco__f3e6b6_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['data_cadastro'], name='core_animal_data_ca_c8f8d9_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['data_atualizacao'], name='core_animal_data_at_3e30de_idx'),
        ),
    ]
