# Generated by Django 5.0 on 2025-02-17 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_animal_core_animal_usuario_544308_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteLegado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('percentual_desconto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_eduzz_antigo', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente Legado',
                'verbose_name_plural': 'Clientes Legados',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='eduzztransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transação Eduzz', 'verbose_name_plural': 'Transações Eduzz'},
        ),
        migrations.AddField(
            model_name='eduzztransaction',
            name='data_expiracao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eduzztransaction',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eduzztransaction',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eduzztransaction',
            name='plano',
            field=models.CharField(choices=[('mensal', 'Mensal'), ('anual', 'Anual'), ('cortesia', 'Cortesia')], default='mensal', max_length=20),
        ),
        migrations.AddField(
            model_name='eduzztransaction',
            name='valor_original',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='eduzztransaction',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='eduzztransaction',
            name='webhook_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eduzztransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('canceled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='eduzztransaction',
            name='cliente_legado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.clientelegado'),
        ),
    ]
