# Generated by Django 5.0 on 2025-02-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_clientelegado_alter_eduzztransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientelegado',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
