# Generated by Django 5.0 on 2025-02-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.AddField(
            model_name='profile',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
