# Generated by Django 5.0 on 2025-02-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_usersubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubscription',
            options={},
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='is_legacy',
            field=models.BooleanField(default=False, help_text='Cliente legado (sem adesão)'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='eduzz_subscription_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='plan_type',
            field=models.CharField(choices=[('mensal', 'Mensal'), ('anual', 'Anual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('pending', 'Pendente'), ('cancelled', 'Cancelado'), ('expired', 'Expirado'), ('trial', 'Trial')], max_length=20),
        ),
    ]
