# Generated by Django 5.0 on 2025-02-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_usuarioeduzz'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePlanilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('eduzz_customer_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Cliente Planilha',
                'verbose_name_plural': 'Clientes Planilha',
            },
        ),
    ]
