# Generated by Django 5.0 on 2025-03-05 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_eduzzcontract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento Stripe',
                'verbose_name_plural': 'Eventos Stripe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StripeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_product_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto Stripe',
                'verbose_name_plural': 'Produtos Stripe',
            },
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente Stripe',
                'verbose_name_plural': 'Clientes Stripe',
            },
        ),
        migrations.CreateModel(
            name='StripePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(max_length=100, unique=True)),
                ('currency', models.CharField(default='brl', max_length=3)),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recurring_interval', models.CharField(blank=True, choices=[('day', 'Diário'), ('week', 'Semanal'), ('month', 'Mensal'), ('year', 'Anual')], max_length=10, null=True)),
                ('recurring_interval_count', models.IntegerField(blank=True, default=1, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.stripeproduct')),
            ],
            options={
                'verbose_name': 'Preço Stripe',
                'verbose_name_plural': 'Preços Stripe',
            },
        ),
        migrations.CreateModel(
            name='StripeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('past_due', 'Pagamento Atrasado'), ('unpaid', 'Não Pago'), ('canceled', 'Cancelado'), ('incomplete', 'Incompleto'), ('incomplete_expired', 'Incompleto Expirado'), ('trialing', 'Em Teste')], max_length=20)),
                ('plan_type', models.CharField(choices=[('mensal', 'Mensal'), ('anual', 'Anual'), ('cortesia', 'Cortesia')], max_length=20)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('is_trial', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stripeprice')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assinatura Stripe',
                'verbose_name_plural': 'Assinaturas Stripe',
            },
        ),
        migrations.CreateModel(
            name='StripeInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_invoice_id', models.CharField(max_length=100, unique=True)),
                ('stripe_customer_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('open', 'Aberta'), ('paid', 'Paga'), ('uncollectible', 'Não Cobrável'), ('void', 'Anulada')], max_length=20)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='brl', max_length=3)),
                ('invoice_date', models.DateTimeField()),
                ('invoice_pdf', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stripesubscription')),
            ],
            options={
                'verbose_name': 'Fatura Stripe',
                'verbose_name_plural': 'Faturas Stripe',
            },
        ),
    ]
