# Generated by Django 5.0 on 2025-03-08 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_stripeevent_stripeproduct_stripecustomer_stripeprice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroMorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_morte', models.DateField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('prejuizo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_morte', to='core.animal')),
            ],
            options={
                'verbose_name': 'Registro de Morte',
                'verbose_name_plural': 'Registros de Morte',
                'ordering': ['-data_morte'],
            },
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='user',
        ),
        migrations.DeleteModel(
            name='StripeEvent',
        ),
        migrations.RemoveField(
            model_name='stripeinvoice',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='stripeprice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stripesubscription',
            name='price',
        ),
        migrations.RemoveField(
            model_name='stripesubscription',
            name='user',
        ),
        migrations.AddField(
            model_name='motivomorte',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registromorte',
            name='motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_morte', to='core.motivomorte'),
        ),
        migrations.AddField(
            model_name='registromorte',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_morte', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='StripeCustomer',
        ),
        migrations.DeleteModel(
            name='StripeInvoice',
        ),
        migrations.DeleteModel(
            name='StripeProduct',
        ),
        migrations.DeleteModel(
            name='StripePrice',
        ),
        migrations.DeleteModel(
            name='StripeSubscription',
        ),
    ]
