# Generated by Django 5.0 on 2025-03-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_create_registro_morte'),
    ]

    operations = [
    ]
