# Generated by Django 5.0 on 2025-03-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_animal_estacao_monta'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabancaria',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Inicial'),
        ),
    ]
