# Generated by Django 5.0 on 2025-03-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_stripecustomer_stripeevent_stripeinvoice_stripeprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fazenda',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Logo'),
        ),
    ]
