# Generated by Django 5.0 on 2025-03-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_fazenda_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='boleto',
            field=models.FileField(blank=True, null=True, upload_to='despesas/boletos/', verbose_name='Boleto'),
        ),
    ]
