# Generated by Django 5.0 on 2025-03-27 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_insumo_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='fazenda_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_origem', to='core.fazenda', verbose_name='Fazenda de Origem'),
        ),
    ]
